apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opensearchclusters.opensearch.opensearch.org
spec:
  group: opensearch.opensearch.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                nodePools:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      replicas:
                        type: integer
                      roles:
                        type: array
                        items:
                          type: string
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
  scope: Namespaced
  names:
    plural: opensearchclusters
    singular: opensearchcluster
    kind: OpenSearchCluster
    shortNames:
    - osc