apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opensearch-operator
  template:
    metadata:
      labels:
        name: opensearch-operator
    spec:
      serviceAccountName: opensearch-operator
      containers:
        - name: opensearch-operator
          image: opensearchproject/opensearch-operator:latest
          ports:
            - containerPort: 60000
              name: metrics
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "opensearch-operator"