apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opensearch-operator
subjects:
  - kind: ServiceAccount
    name: opensearch-operator
    namespace: opensearch-operator